import { delay, http, HttpResponse } from 'msw'
import { screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { apiBaseUrl, mockAuthenticatedBootstrap } from '../../../tests/authHandlers'
import { renderWithProviders } from '../../../tests/renderApp'
import { LeadsPage } from '../pages/LeadsPage'
import { server } from '../../../tests/server'

const lead = { id: 7, nome: 'Maria', sobrenome: 'Souza', email: 'maria@example.com', telefone: '11999999999', status: 'NOVO', prioridade: 'ALTA', criado_em: '2026-07-15T18:30:00Z', atualizado_em: '2026-07-16T18:30:00Z' }
const list = (results = [lead]) => ({ count: results.length, next: null, previous: null, results })
function boot(results = [lead]) { mockAuthenticatedBootstrap(); server.use(http.get(`${apiBaseUrl}/leads/`, () => HttpResponse.json(list(results)))) }

describe('gestao visual de leads', () => {
  it('exibe loading e lista leads em tabela acessivel', async () => { mockAuthenticatedBootstrap(); server.use(http.get(`${apiBaseUrl}/leads/`, async () => { await delay(30); return HttpResponse.json(list()) })); renderWithProviders(<LeadsPage />, '/app/leads'); expect(await screen.findByRole('heading', { name: 'Leads' })).toBeInTheDocument(); expect(await screen.findByRole('link', { name: 'Visualizar Maria Souza' })).toBeInTheDocument(); expect(screen.getAllByLabelText('Status: Novo')).not.toHaveLength(0) })
  it('diferencia estado vazio e resultado vazio por filtros', async () => { boot([]); renderWithProviders(<LeadsPage />, '/app/leads'); expect(await screen.findByText('Ainda nao ha leads cadastrados')).toBeInTheDocument(); boot([]); renderWithProviders(<LeadsPage />, '/app/leads?status=NOVO'); expect(await screen.findByText('Nenhum resultado para estes filtros')).toBeInTheDocument() })
  it('envia busca com debounce para a API', async () => { let search = ''; mockAuthenticatedBootstrap(); server.use(http.get(`${apiBaseUrl}/leads/`, ({ request }) => { search = new URL(request.url).searchParams.get('search') || ''; return HttpResponse.json(list()) })); renderWithProviders(<LeadsPage />, '/app/leads?page=3'); const input = await screen.findByRole('textbox', { name: 'Buscar leads' }); await userEvent.type(input, 'maria'); expect(search).toBe(''); await waitFor(() => expect(search).toBe('maria'), { timeout: 1000 }) })
  it('envia filtros, ordenacao e page_size', async () => { let query = ''; mockAuthenticatedBootstrap(); server.use(http.get(`${apiBaseUrl}/leads/`, ({ request }) => { query = new URL(request.url).search; return HttpResponse.json(list()) })); renderWithProviders(<LeadsPage />, '/app/leads'); await screen.findByRole('heading', { name: 'Leads' }); await userEvent.selectOptions(screen.getByRole('combobox', { name: 'Status' }), 'VENDIDO'); await userEvent.selectOptions(screen.getByRole('combobox', { name: 'Prioridade' }), 'ALTA'); await userEvent.click(screen.getByRole('button', { name: 'Nome' })); await userEvent.selectOptions(screen.getByRole('combobox', { name: /Por pagina/i }), '50'); await waitFor(() => expect(query).toContain('page_size=50')); expect(query).toContain('status=VENDIDO'); expect(query).toContain('prioridade=ALTA'); expect(query).toContain('ordering=nome') })
  it('restaura filtros da URL, aplica ordenacao padrao e reinicia a pagina ao filtrar', async () => { let query = ''; mockAuthenticatedBootstrap(); server.use(http.get(`${apiBaseUrl}/leads/`, ({ request }) => { query = new URL(request.url).search; return HttpResponse.json(list()) })); renderWithProviders(<LeadsPage />, '/app/leads?page=3&page_size=50&status=NOVO&criado_em_de=2026-01-01&criado_em_ate=2026-12-31'); expect(await screen.findByRole('combobox', { name: 'Status' })).toHaveValue('NOVO'); expect(screen.getByRole('combobox', { name: 'Ordenar por' })).toHaveValue('-criado_em'); expect(query).toContain('ordering=-criado_em'); await userEvent.selectOptions(screen.getByRole('combobox', { name: 'Prioridade' }), 'ALTA'); await waitFor(() => expect(query).toContain('page=1')); expect(query).toContain('prioridade=ALTA'); expect(screen.getByText('4 filtros ativos')).toBeInTheDocument() })
  it('disponibiliza filtros avancados no dialogo movel', async () => { boot(); renderWithProviders(<LeadsPage />, '/app/leads'); await screen.findByRole('heading', { name: 'Leads' }); await userEvent.click(screen.getByRole('button', { name: 'Filtros' })); expect(screen.getByRole('dialog', { name: 'Filtros de leads' })).toBeInTheDocument(); expect(screen.getAllByRole('combobox', { name: 'Ordenar por' })).toHaveLength(2); await userEvent.click(screen.getByRole('button', { name: 'Concluir' })); expect(screen.queryByRole('dialog', { name: 'Filtros de leads' })).not.toBeInTheDocument() })
  it('cria lead sem responsavel e mostra feedback', async () => { let payload: Record<string, unknown> = {}; boot(); server.use(http.post(`${apiBaseUrl}/leads/`, async ({ request }) => { payload = await request.json() as Record<string, unknown>; return HttpResponse.json({ ...lead, id: 8, ...payload }, { status: 201 }) })); renderWithProviders(<LeadsPage />, '/app/leads'); await screen.findByRole('heading', { name: 'Leads' }); await userEvent.click(screen.getByRole('button', { name: 'Novo lead' })); await userEvent.type(screen.getByLabelText('Nome'), 'Joana'); await userEvent.type(screen.getByLabelText('E-mail'), 'joana@example.com'); await userEvent.click(screen.getByRole('button', { name: 'Criar lead' })); await waitFor(() => expect(payload.nome).toBe('Joana')); expect(payload).not.toHaveProperty('agente_responsavel'); expect(await screen.findByText('Lead criado com sucesso.')).toBeInTheDocument() })
  it('mostra validacao local do formulario', async () => { boot(); renderWithProviders(<LeadsPage />, '/app/leads'); await screen.findByRole('heading', { name: 'Leads' }); await userEvent.click(screen.getByRole('button', { name: 'Novo lead' })); await userEvent.click(screen.getByRole('button', { name: 'Criar lead' })); expect(await screen.findByText('Informe o nome.')).toBeInTheDocument() })
})
