import { z } from 'zod'
import { leadPriorities, leadStatuses, type CreateLeadPayload, type LeadFilters } from '../types/lead'
const optionalText = (max: number) => z.string().trim().max(max).optional().or(z.literal(''))
export const leadSchema = z.object({ id: z.number().int().positive(), nome: z.string().trim().min(1).max(255), sobrenome: z.string().max(100).nullable(), email: z.string().email().max(254), telefone: z.string().max(20).nullable(), status: z.enum(leadStatuses), prioridade: z.enum(leadPriorities), criado_em: z.string().datetime({ offset: true }), atualizado_em: z.string().datetime({ offset: true }) })
export const leadListResponseSchema = z.object({ count: z.number().int().nonnegative(), next: z.string().nullable(), previous: z.string().nullable(), results: z.array(leadSchema) })
export const leadFormSchema = z.object({ nome: z.string().trim().min(1, 'Informe o nome.').max(255, 'Use no maximo 255 caracteres.'), sobrenome: optionalText(100), email: z.string().trim().email('Informe um e-mail valido.').max(254), telefone: optionalText(20), status: z.enum(leadStatuses), prioridade: z.enum(leadPriorities) })
export const leadFiltersSchema = z.object({ page: z.number().int().positive().catch(1), pageSize: z.number().int().min(1).max(100).catch(20), search: z.string().trim().max(255).optional(), status: z.enum(leadStatuses).optional(), prioridade: z.enum(leadPriorities).optional(), criadoEmDe: z.string().date().optional(), criadoEmAte: z.string().date().optional(), ordering: z.enum(['nome', '-nome', 'email', '-email', 'status', '-status', 'prioridade', '-prioridade', 'criado_em', '-criado_em', 'atualizado_em', '-atualizado_em']).optional() }).superRefine((filters, context) => { if (filters.criadoEmDe && filters.criadoEmAte && filters.criadoEmDe > filters.criadoEmAte) context.addIssue({ code: 'custom', path: ['criadoEmAte'], message: 'A data final deve ser posterior ou igual a inicial.' }) })
export type LeadFormValues = z.infer<typeof leadFormSchema>
export function toLeadPayload(values: LeadFormValues): CreateLeadPayload { return { ...values, sobrenome: values.sobrenome || null, telefone: values.telefone || null } }
export function parseLeadFilters(value: unknown): LeadFilters { return leadFiltersSchema.parse(value) }
