import { http, HttpResponse } from 'msw'
import { screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { vi } from 'vitest'
import { apiBaseUrl, mockAuthenticatedBootstrap } from '../../../tests/authHandlers'
import { renderWithProviders } from '../../../tests/renderApp'
import { server } from '../../../tests/server'
import { DashboardPage } from '../pages/DashboardPage'

vi.mock('react-chartjs-2', () => ({ Bar: ({ data, 'aria-label': label }: { data: { labels: string[] }; 'aria-label': string }) => <div aria-label={label}>{data.labels.join(', ')}</div>, Doughnut: ({ data, 'aria-label': label }: { data: { labels: string[] }; 'aria-label': string }) => <div aria-label={label}>{data.labels.join(', ')}</div> }))
const summary = { period: { key: '30d', date_from: '2026-06-16', date_to: '2026-07-15' }, metrics: { total_leads: 3, created_today: 1, created_in_period: 2, converted_in_period: 1, conversion_rate: 50 }, by_status: [{ status: 'NOVO', label: 'Novo', count: 2 }, { status: 'VENDIDO', label: 'Vendido', count: 1 }], by_priority: [{ priority: 'BAIXA', label: 'Baixa', count: 0 }, { priority: 'ALTA', label: 'Alta', count: 3 }], monthly_evolution: [{ month: '2026-06', label: 'Jun/2026', count: 0 }, { month: '2026-07', label: 'Jul/2026', count: 2 }], recent_leads: [{ id: 7, nome: 'Maria', sobrenome: 'Souza', email: 'maria@example.com', status: 'NOVO', prioridade: 'ALTA', criado_em: '2026-07-15T18:30:00Z' }], interaction_total: 5, interaction_by_type: [{ tipo: 'LIGACAO', label: 'Ligacao', count: 2 }, { tipo: 'EMAIL', label: 'E-mail', count: 1 }, { tipo: 'REUNIAO', label: 'Reuniao', count: 0 }, { tipo: 'MENSAGEM', label: 'Mensagem', count: 2 }, { tipo: 'NOTA', label: 'Nota', count: 0 }], leads_with_interaction: 2, leads_without_interaction: 1, interaction_monthly_evolution: [{ month: '2026-06', label: 'Jun/2026', count: 0 }, { month: '2026-07', label: 'Jul/2026', count: 5 }] }
function boot(response = summary) { mockAuthenticatedBootstrap(); server.use(http.get(`${apiBaseUrl}/dashboard/summary/`, () => HttpResponse.json(response))) }
describe('dashboard funcional', () => {
  it('renderiza metricas, graficos com resumo e link de lead recente', async () => { boot(); renderWithProviders(<DashboardPage />); expect(await screen.findByRole('heading', { name: 'Dashboard' })).toBeInTheDocument(); expect(screen.getByText('Total de leads')).toBeInTheDocument(); expect(screen.getByText('Total de interacoes')).toBeInTheDocument(); expect(screen.getByText('Leads com interacao')).toBeInTheDocument(); expect(screen.getByText('Leads sem interacao')).toBeInTheDocument(); expect(screen.getByLabelText('Grafico de evolucao mensal')).toHaveTextContent('Jun/2026, Jul/2026'); expect(screen.getByLabelText('Grafico de evolucao de interacoes')).toHaveTextContent('Jun/2026, Jul/2026'); expect(screen.getByLabelText('Grafico de interacoes por tipo')).toHaveTextContent('Ligacao, E-mail, Reuniao, Mensagem, Nota'); expect(screen.getByText('Reuniao:')).toBeInTheDocument(); expect(screen.getByRole('link', { name: /Maria Souza/i })).toHaveAttribute('href', '/app/leads/7') })
  it('usa periodo da URL e envia o filtro para a API', async () => { let period = ''; mockAuthenticatedBootstrap(); server.use(http.get(`${apiBaseUrl}/dashboard/summary/`, ({ request }) => { period = new URL(request.url).searchParams.get('period') ?? ''; return HttpResponse.json({ ...summary, period: { ...summary.period, key: '7d' } }) })); renderWithProviders(<DashboardPage />, '/app?period=7d'); await screen.findByRole('heading', { name: 'Dashboard' }); await waitFor(() => expect(period).toBe('7d')) })
  it('usa a mesma query para todos os periodos predefinidos', async () => { const periods: string[] = []; mockAuthenticatedBootstrap(); server.use(http.get(`${apiBaseUrl}/dashboard/summary/`, ({ request }) => { const period = new URL(request.url).searchParams.get('period') ?? ''; periods.push(period); return HttpResponse.json({ ...summary, period: { ...summary.period, key: period } }) })); for (const period of ['7d', '30d', '90d', '12m']) { const view = renderWithProviders(<DashboardPage />, `/app?period=${period}`); await waitFor(() => expect(periods).toContain(period)); view.unmount() } expect(periods).toEqual(['7d', '30d', '90d', '12m']) })
  it('troca para periodo personalizado e valida intervalo incompleto', async () => { let query = ''; mockAuthenticatedBootstrap(); server.use(http.get(`${apiBaseUrl}/dashboard/summary/`, ({ request }) => { query = new URL(request.url).search; return HttpResponse.json({ ...summary, period: { ...summary.period, key: 'custom' } }) })); renderWithProviders(<DashboardPage />); await screen.findByRole('heading', { name: 'Dashboard' }); await userEvent.selectOptions(screen.getByLabelText('Periodo'), 'custom'); await userEvent.click(screen.getByRole('button', { name: 'Aplicar' })); expect(await screen.findByRole('alert')).toHaveTextContent('Informe as duas datas'); await userEvent.type(screen.getByLabelText('Data inicial'), '2026-06-01'); await userEvent.type(screen.getByLabelText('Data final'), '2026-06-30'); await userEvent.click(screen.getByRole('button', { name: 'Aplicar' })); await waitFor(() => expect(query).toContain('period=custom')) })
  it('mostra estado vazio preservando o dashboard', async () => { boot({ ...summary, metrics: { total_leads: 0, created_today: 0, created_in_period: 0, converted_in_period: 0, conversion_rate: 0 }, recent_leads: [] }); renderWithProviders(<DashboardPage />); expect(await screen.findByText('Seu dashboard esta pronto para comecar')).toBeInTheDocument() })
  it('mantem analiticos com zero quando ha leads sem interacoes', async () => { boot({ ...summary, interaction_total: 0, interaction_by_type: summary.interaction_by_type.map((item) => ({ ...item, count: 0 })), leads_with_interaction: 0, leads_without_interaction: 3, interaction_monthly_evolution: summary.interaction_monthly_evolution.map((item) => ({ ...item, count: 0 })) }); renderWithProviders(<DashboardPage />); expect(await screen.findByText('Total de interacoes')).toBeInTheDocument(); expect(screen.getAllByText('0', { selector: 'p' })).not.toHaveLength(0); expect(screen.getByText('Leads sem interacao')).toBeInTheDocument(); expect(screen.getByLabelText('Grafico de interacoes por tipo')).toHaveTextContent('Ligacao, E-mail, Reuniao, Mensagem, Nota') })
  it('normaliza resposta invalida e permite tentar novamente', async () => { mockAuthenticatedBootstrap(); let valid = false; server.use(http.get(`${apiBaseUrl}/dashboard/summary/`, () => valid ? HttpResponse.json(summary) : HttpResponse.json({ unexpected: true }))); renderWithProviders(<DashboardPage />); expect(await screen.findByRole('alert')).toHaveTextContent('formato inesperado'); valid = true; await userEvent.click(screen.getByRole('button', { name: 'Tentar novamente' })); expect(await screen.findByRole('heading', { name: 'Dashboard' })).toBeInTheDocument() })
})
