import { Search, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { leadPriorities, leadStatuses, type LeadFilters, type LeadPriority, type LeadStatus } from '../types/lead'
import { priorityLabels, statusLabels } from '../utils/leadFormatters'
export function LeadFilters({ filters, onChange, onClear }: { filters: LeadFilters; onChange: (patch: Partial<LeadFilters>) => void; onClear: () => void }) {
  const [search, setSearch] = useState(filters.search || '')
  useEffect(() => setSearch(filters.search || ''), [filters.search])
  useEffect(() => { const timer = window.setTimeout(() => { if (search !== (filters.search || '')) onChange({ search: search || undefined }) }, 400); return () => window.clearTimeout(timer) }, [search, filters.search, onChange])
  return <section className="rounded-2xl border border-line bg-panel p-4" aria-label="Filtros de leads"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="relative lg:col-span-2"><span className="sr-only">Buscar leads</span><Search className="pointer-events-none absolute left-3 top-3.5 size-4 text-muted" /><input className="field-input pl-10" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar nome, e-mail ou telefone" /></label><label><span className="sr-only">Status</span><select className="field-input" value={filters.status || ''} onChange={(event) => onChange({ status: (event.target.value || undefined) as LeadStatus | undefined })}><option value="">Todos os status</option>{leadStatuses.map((status) => <option key={status} value={status}>{statusLabels[status]}</option>)}</select></label><label><span className="sr-only">Prioridade</span><select className="field-input" value={filters.prioridade || ''} onChange={(event) => onChange({ prioridade: (event.target.value || undefined) as LeadPriority | undefined })}><option value="">Todas as prioridades</option>{leadPriorities.map((priority) => <option key={priority} value={priority}>{priorityLabels[priority]}</option>)}</select></label><button className="secondary-button justify-center" type="button" onClick={onClear}><X className="size-4" />Limpar filtros</button></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label><span className="field-label">Criado a partir de</span><input className="field-input" type="date" value={filters.criadoEmDe || ''} onChange={(event) => onChange({ criadoEmDe: event.target.value || undefined })} /></label><label><span className="field-label">Criado ate</span><input className="field-input" type="date" value={filters.criadoEmAte || ''} onChange={(event) => onChange({ criadoEmAte: event.target.value || undefined })} /></label></div></section>
}
