import { ChevronDown, ChevronUp, Eye, Pencil, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { LeadCard } from './LeadCard'
import { LeadPriorityBadge } from './LeadPriorityBadge'
import { LeadStatusBadge } from './LeadStatusBadge'
import type { Lead, LeadOrdering } from '../types/lead'
import { formatLeadDate, leadFullName } from '../utils/leadFormatters'
const sortable: Array<[string, Exclude<LeadOrdering, `-${string}`>]> = [['Nome', 'nome'], ['E-mail', 'email'], ['Status', 'status'], ['Prioridade', 'prioridade'], ['Criado em', 'criado_em']]
export function LeadTable({ leads, ordering, onOrder, onEdit, onDelete }: { leads: Lead[]; ordering?: LeadOrdering; onOrder: (value: LeadOrdering) => void; onEdit: (lead: Lead) => void; onDelete: (lead: Lead) => void }) {
  const nextOrder = (field: Exclude<LeadOrdering, `-${string}`>): LeadOrdering => ordering === field ? `-${field}` : field
  return <><div className="grid gap-3 md:hidden">{leads.map((lead) => <LeadCard key={lead.id} lead={lead} onEdit={onEdit} onDelete={onDelete} />)}</div><div className="hidden overflow-x-auto rounded-2xl border border-line bg-panel md:block"><table className="w-full text-left text-sm"><thead className="border-b border-line bg-canvas text-muted"><tr>{sortable.map(([label, field]) => <th key={field} scope="col" className="px-4 py-3 font-medium"><button type="button" className="inline-flex items-center gap-1 hover:text-strong" onClick={() => onOrder(nextOrder(field))}>{label}{ordering?.replace('-', '') === field && (ordering.startsWith('-') ? <ChevronDown className="size-4" /> : <ChevronUp className="size-4" />)}</button></th>)}<th scope="col" className="px-4 py-3 font-medium">Telefone</th><th scope="col" className="px-4 py-3 font-medium">Acoes</th></tr></thead><tbody>{leads.map((lead) => <tr key={lead.id} className="border-b border-line last:border-0"><td className="px-4 py-4 font-medium text-strong">{leadFullName(lead)}</td><td className="px-4 py-4 text-muted">{lead.email}</td><td className="px-4 py-4"><LeadStatusBadge status={lead.status} /></td><td className="px-4 py-4"><LeadPriorityBadge prioridade={lead.prioridade} /></td><td className="px-4 py-4 text-muted">{formatLeadDate(lead.criado_em)}</td><td className="px-4 py-4 text-muted">{lead.telefone || '—'}</td><td className="px-4 py-4"><div className="flex gap-1"><Link className="icon-button" aria-label={`Visualizar ${leadFullName(lead)}`} to={`/app/leads/${lead.id}`}><Eye className="size-4" /></Link><button className="icon-button" type="button" aria-label={`Editar ${leadFullName(lead)}`} onClick={() => onEdit(lead)}><Pencil className="size-4" /></button><button className="icon-button text-danger" type="button" aria-label={`Excluir ${leadFullName(lead)}`} onClick={() => onDelete(lead)}><Trash2 className="size-4" /></button></div></td></tr>)}</tbody></table></div></>
}
