# Generated by Django 6.0.1 on 2026-01-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_agente_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
