import { Plus, RefreshCw } from 'lucide-react'
import { useCallback, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { normalizeApiError } from '../../../lib/errors/normalizeApiError'
import { DeleteLeadDialog } from '../components/DeleteLeadDialog'
import { LeadFilters } from '../components/LeadFilters'
import { LeadFormDialog } from '../components/LeadFormDialog'
import { LeadTable } from '../components/LeadTable'
import { useLeads } from '../hooks/useLeads'
import { leadFiltersSchema } from '../schemas/leadSchema'
import type { Lead, LeadFilters as Filters, LeadOrdering } from '../types/lead'
export function LeadsPage() {
  const [params, setParams] = useSearchParams(); const [editing, setEditing] = useState<Lead | undefined>(); const [deleting, setDeleting] = useState<Lead | undefined>(); const [createOpen, setCreateOpen] = useState(false); const [feedback, setFeedback] = useState<string | null>(null)
  const filters = useMemo(() => leadFiltersSchema.parse({ page: Number(params.get('page') || 1), pageSize: Number(params.get('page_size') || 20), search: params.get('search') || undefined, status: params.get('status') || undefined, prioridade: params.get('prioridade') || undefined, criadoEmDe: params.get('criado_em_de') || undefined, criadoEmAte: params.get('criado_em_ate') || undefined, ordering: params.get('ordering') || undefined }), [params])
  const leads = useLeads(filters)
  const setFilters = useCallback((patch: Partial<Filters>, resetPage = true) => { const next = { ...filters, ...patch, page: resetPage ? 1 : patch.page || filters.page }; const parsed = leadFiltersSchema.safeParse(next); if (!parsed.success) return; const query = new URLSearchParams(); query.set('page', String(parsed.data.page)); query.set('page_size', String(parsed.data.pageSize)); if (parsed.data.search) query.set('search', parsed.data.search); if (parsed.data.status) query.set('status', parsed.data.status); if (parsed.data.prioridade) query.set('prioridade', parsed.data.prioridade); if (parsed.data.criadoEmDe) query.set('criado_em_de', parsed.data.criadoEmDe); if (parsed.data.criadoEmAte) query.set('criado_em_ate', parsed.data.criadoEmAte); if (parsed.data.ordering) query.set('ordering', parsed.data.ordering); setParams(query) }, [filters, setParams])
  const clear = () => setParams({ page: '1', page_size: '20' }); const hasFilters = Boolean(filters.search || filters.status || filters.prioridade || filters.criadoEmDe || filters.criadoEmAte)
  const success = (message: string) => setFeedback(message)
  if (leads.isError) { const error = normalizeApiError(leads.error); return <section className="state-card" role="alert"><h1 className="text-2xl font-semibold text-strong">Nao foi possivel carregar os leads</h1><p className="mt-2 text-muted">{error.message}</p><button className="secondary-button mt-5" type="button" onClick={() => void leads.refetch()}><RefreshCw className="size-4" />Tentar novamente</button></section> }
  const pageCount = Math.max(1, Math.ceil((leads.data?.count || 0) / filters.pageSize))
  return <><section className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-brand">Relacionamento</p><h1 className="mt-1 text-3xl font-semibold text-strong">Leads</h1><p className="mt-2 text-muted">Gerencie seus contatos sem sair da pagina.</p></div><button className="primary-button w-auto" type="button" onClick={() => setCreateOpen(true)}><Plus className="size-4" />Novo lead</button></section>{feedback && <p className="mt-5 rounded-xl bg-brand-soft px-4 py-3 text-sm text-strong" role="status">{feedback}</p>}<div className="mt-6"><LeadFilters filters={filters} onChange={setFilters} onClear={clear} /></div>{leads.isLoading ? <div className="mt-6 grid gap-3"><div className="skeleton h-36" /><div className="skeleton h-36" /></div> : leads.data?.results.length ? <><div className="mt-6"><LeadTable leads={leads.data.results} ordering={filters.ordering} onOrder={(ordering: LeadOrdering) => setFilters({ ordering })} onEdit={setEditing} onDelete={setDeleting} /></div><nav className="mt-5 flex flex-wrap items-center justify-between gap-3" aria-label="Paginacao"><p className="text-sm text-muted">Pagina {filters.page} de {pageCount} · {leads.data.count} registros</p><div className="flex items-center gap-2"><label className="text-sm text-muted">Por pagina <select className="ml-1 rounded-lg border border-line bg-panel p-2" value={filters.pageSize} onChange={(event) => setFilters({ pageSize: Number(event.target.value) })}>{[10, 20, 50, 100].map((size) => <option key={size}>{size}</option>)}</select></label><button className="secondary-button" type="button" disabled={filters.page <= 1} aria-label="Pagina anterior" onClick={() => setFilters({ page: filters.page - 1 }, false)}>Anterior</button><button className="secondary-button" type="button" disabled={filters.page >= pageCount} aria-label="Proxima pagina" onClick={() => setFilters({ page: filters.page + 1 }, false)}>Proxima</button></div></nav></> : <section className="state-card mt-6"><h2 className="text-xl font-semibold text-strong">{hasFilters ? 'Nenhum resultado para estes filtros' : 'Ainda nao ha leads cadastrados'}</h2><p className="mt-2 text-muted">{hasFilters ? 'Altere ou limpe os filtros para consultar outros contatos.' : 'Crie o primeiro lead para iniciar o acompanhamento.'}</p><button className="primary-button mt-5 w-auto" type="button" onClick={() => hasFilters ? clear() : setCreateOpen(true)}>{hasFilters ? 'Limpar filtros' : 'Criar primeiro lead'}</button></section>}{createOpen && <LeadFormDialog onClose={() => setCreateOpen(false)} onSuccess={success} />}{editing && <LeadFormDialog lead={editing} onClose={() => setEditing(undefined)} onSuccess={success} />}{deleting && <DeleteLeadDialog lead={deleting} onClose={() => setDeleting(undefined)} onSuccess={() => { success('Lead excluido com sucesso.'); setDeleting(undefined) }} />}</>
}
